site_name: Manual de recepción
site_description: "Documentación oficial para el equipo de recepción del Hotel Erbon"
site_author: "Hotel Erbon"
site_url: "https://hotel-erbon.com"

nav:
  - Estado: index.md
  - Recepción:
      - Rack: rack.md
  - Check-In:
      - Proceso de Registro: checkin_proceso.md
      - Configuración de Habitaciones: checkin_habitaciones.md
      - Gestión de Documentos: checkin_documentos.md
  - Check-Out:
      - Proceso de Salida: checkout_proceso.md
      - Facturación: checkout_facturacion.md
  - Reservas:
      - Crear y Modificar Reservas: reservas_crear.md
      - Cancelaciones: reservas_cancelaciones.md
  - Reportes:
      - Reportes Diario: reportes_diario.md
      - Historial de Reservas: reportes_historial.md

theme:
  name: material
  palette:
    primary: "#015442"  # Color representativo del hotel
    # accent: "teal"
  font:
    text: "Open Sans"
    code: "Roboto Mono"
  favicon: "images/favicon.ico"
  logo: "img/logo.png"
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - search.highlight
  language: es

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - footnotes

extra_css:
  - styles/custom.css

plugins:
  - search

extra_css:
  - styles/custom.css
